export const BOARD_LIST = 'BOARD_LIST';
export const BOARD_LIST_SUCCESS = 'BOARD_LIST_SUCCESS';
export const BOARD_LIST_FAILURE = 'BOARD_LIST_FAILURE';

export const BOARD_WRITE = 'BOARD_WRITE';
export const BOARD_WRITE_SUCCESS = 'BOARD_WRITE_SUCCESS';
export const BOARD_WRITE_FAILURE = 'BOARD_WRITE_FAILURE';

export const BOARD_DETAIL = 'BOARD_DETAIL';
export const BOARD_DETAIL_SUCCESS = 'BOARD_DETAIL_SUCCESS';
export const BOARD_DETAIL_FAILURE = 'BOARD_DETAIL_FAILURE';

export const MEMBER_LOGIN = 'MEMBER_LOGIN';
export const MEMBER_LOGIN_SUCCESS = 'MEMBER_LOGIN_SUCCESS';
export const MEMBER_LOGIN_FAILURE = 'MEMBER_LOGIN_FAILURE';

export const MEMBER_REGISTER = 'MEMBER_REGISTER';
export const MEMBER_REGISTER_SUCCESS = 'MEMBER_REGISTER_SUCCESS';
export const MEMBER_REGISTER_FAILURE = 'MEMBER_REGISTER_FAILURE';

export const MEMBER_CHECKID = 'MEMBER_CHECKID';
export const MEMBER_CHECKID_SUCCESS = 'MEMBER_CHECKID_SUCCESS';
export const MEMBER_CHECKID_FAILURE = 'MEMBER_CHECKID_FAILURE';

export const MEMBER_CHECKEMAIL = 'MEMBER_CHECKEMAIL';
export const MEMBER_CHECKEMAIL_SUCCESS = 'MEMBER_CHECKEMAIL_SUCCESS';
export const MEMBER_CHECKEMAIL_FAILURE = 'MEMBER_CHECKEMAIL_FAILURE';

export const MEMBER_CHECKTOKEN = 'MEMBER_CHECKTOKEN';
export const MEMBER_CHECKTOKEN_SUCCESS = 'MEMBER_CHECKTOKEN_SUCCESS';
export const MEMBER_CHECKTOKEN_FAILURE = 'MEMBER_CHECKTOKEN_FAILURE';

export const MEMBER_ACCOUNT = 'MEMBER_ACCOUNT';
export const MEMBER_ACCOUNT_SUCCESS = 'MEMBER_ACCOUNT_SUCCESS';
export const MEMBER_ACCOUNT_FAILURE = 'MEMBER_ACCOUNT_FAILURE';

export const MEMBER_MODIFY = 'MEMBER_MODIFY';
export const MEMBER_MODIFY_SUCCESS = 'MEMBER_MODIFY_SUCCESS';
export const MEMBER_MODIFY_FAILURE = 'MEMBER_MODIFY_FAILURE';

export const MEMBER_PROFILE =  'MEMBER_PROFILE';
export const MEMBER_PROFILE_SUCCESS = 'MEMBER_PROFILE_SUCCESS';
export const MEMBER_PROFILE_FAILURE = 'MEMBER_PROFILE_FAILURE';

export const MEMBER_PROFILE_MODIFY =  'MEMBER_PROFILE_MODIFY';
export const MEMBER_PROFILE_MODIFY_SUCCESS = 'MEMBER_PROFILE_MODIFY_SUCCESS';
export const MEMBER_PROFILE_MODIFY_FAILURE = 'MEMBER_PROFILE_MODIFY_FAILURE';
