export const BOARD_LIST = 'BOARD_LIST';
export const BOARD_LIST_SUCCESS = 'BOARD_LIST_SUCCESS';
export const BOARD_LIST_FAILURE = 'BOARD_LIST_FAILURE';

export const BOARD_WRITE = 'BOARD_WRITE';
export const BOARD_WRITE_SUCCESS = 'BOARD_WRITE_SUCCESS';
export const BOARD_WRITE_FAILURE = 'BOARD_WRITE_FAILURE';